var PHYSICS_DATA = [
  { // ch01 - Mechanical Motion
    id: "ch01",
    g: "8",
    gx: 1,
    title: "Mechanical Motion",
    coverage: "g",
    think: "An object moves from position A to position B. What is the difference between 'distance' and 'displacement'? Can the distance traveled be greater than the displacement? Can an object have zero displacement but non-zero distance?",
    videos: [
      { yt: "MGjkXfc2Hc8", t: "Introduction to Physics" },
      { yt: "bE27l24q1c0", t: "Distance and Displacement" },
      { yt: "pW6mSPPpNj0", t: "Motion in One Dimension" },
      { yt: "ZNte9YPY9RU", t: "Average Speed and Velocity" },
      { yt: "eM1mgEXJfJA", t: "Acceleration" },
      { yt: "vP6_6tGvY3s", t: "Falling Objects" },
      { yt: "vP6_6tGvY3s", t: "Free Fall" },
    ],
    subtopics: [
      { name: "Basic Concepts", vids: [0,1], pq: [0,1,2] },
      { name: "Speed and Velocity", vids: [2,3], pq: [3,4,5,6] },
      { name: "Acceleration", vids: [4,5], pq: [7,8,9,10] },
    ],
    notes: [
      "Distance (s): total path length, scalar (no direction).",
      "Displacement (Δx): change in position, vector (direction matters).",
      "Speed = distance / time. Velocity = displacement / time.",
      "Acceleration (a) = change in velocity / time.",
      "Free fall: g = 9.8 m/s² downward.",
    ],
    practice: [
      {
        q: "A car travels 100 km north, then 60 km south. What is its total distance traveled and its net displacement?",
        options: ["Distance: 160 km, Displacement: 40 km north","Distance: 40 km, Displacement: 160 km north","Distance: 160 km, Displacement: 40 km south","Distance: 100 km, Displacement: 60 km south"],
        ansIdx: 0,
        sol: "Total distance = 100 + 60 = 160 km. Net displacement = 100 − 60 = 40 km north.",
      },
      {
        q: "An object moves with constant velocity of 5 m/s for 10 seconds. What is its acceleration?",
        options: ["0.5 m/s²","5 m/s²","0 m/s²","50 m/s²"],
        ansIdx: 2,
        sol: "Constant velocity means no change in velocity, so acceleration a = Δv/Δt = 0/10 = 0 m/s².",
      },
      {
        q: "A ball is dropped from rest. How far does it fall in 3 seconds? (g = 10 m/s²)",
        options: ["30 m","45 m","90 m","15 m"],
        ansIdx: 1,
        sol: "Using d = ½gt² = ½ × 10 × 3² = ½ × 10 × 9 = 45 m.",
      },
      {
        q: "Which of the following is a vector quantity?",
        options: ["Mass","Distance","Temperature","Velocity"],
        ansIdx: 3,
        sol: "Velocity has both magnitude and direction, making it a vector. Mass, distance, and temperature are scalars.",
      },
      {
        q: "A cyclist travels 200 m in 40 s. What is the average speed?",
        options: ["5 m/s","8 m/s","0.2 m/s","50 m/s"],
        ansIdx: 0,
        sol: "Average speed = distance / time = 200 m / 40 s = 5 m/s.",
      },
    ],
    quiz: [
      {
        q: "Displacement is best described as:",
        options: ["Total path length traveled","The shortest distance from start to end point","The time taken to travel","The speed of an object"],
        ansIdx: 1,
        sol: "Displacement is the vector quantity representing the shortest (straight-line) distance from start to end, with direction.",
      },
      {
        q: "An object accelerates from rest at 2 m/s² for 5 seconds. What is its final velocity?",
        options: ["10 m/s","7 m/s","2.5 m/s","25 m/s"],
        ansIdx: 0,
        sol: "v = at = 2 × 5 = 10 m/s.",
      },
      {
        q: "Which graph shows constant velocity?",
        options: ["A straight line through the origin on a displacement-time graph","A curved line on a velocity-time graph","A horizontal line on a velocity-time graph","A straight line on an acceleration-time graph"],
        ansIdx: 0,
        sol: "Constant velocity appears as a straight line through the origin on a displacement-time (position-time) graph.",
      },
    ],
  },
  { // ch02 - Sound
    id: "ch02",
    g: "8",
    gx: 1,
    title: "Sound and Waves",
    coverage: "g",
    think: "How does sound travel through air? Why can't sound travel through space? What determines whether a sound is high-pitched or loud?",
    videos: [
      { yt: "r-gBw90Tah0", t: "Introduction to Sound" },
      { yt: "r-gBw90Tah0", t: "What is Sound?" },
      { yt: "rqveQowkzzc", t: "Speed of Sound" },
      { yt: "D3R0tq8lT3A", t: "Doppler Effect" },
      { yt: "rqveQowkzzc", t: "Sound Gets Softer" },
      { yt: "qSfMOaem58w", t: "Decibel Scale" },
      { yt: "qSfMOaem58w", t: "Frequency and Pitch" },
      { yt: "qSfMOaem58w", t: "Amplitude" },
    ],
    subtopics: [
      { name: "Sound Basics", vids: [0,1], pq: [0,1] },
      { name: "Wave Properties", vids: [5,6,7], pq: [2,3,4] },
      { name: "Speed of Sound", vids: [2], pq: [5,6,7] },
    ],
    notes: [
      "Sound is a longitudinal wave caused by vibration.",
      "Speed of sound in air ≈ 340 m/s (at 20°C).",
      "Pitch ∝ frequency (high pitch = high frequency).",
      "Loudness ∝ amplitude.",
      "Decibel (dB): log scale for sound intensity.",
    ],
    practice: [
      {
        q: "Sound cannot travel through a vacuum because:",
        options: ["It is too cold","There are no particles to vibrate","Space is too big","Sound is not a wave"],
        ansIdx: 1,
        sol: "Sound requires a medium (particles) to travel. A vacuum has no particles, so sound cannot propagate.",
      },
      {
        q: "A sound wave has frequency 500 Hz. What is its period?",
        options: ["0.002 s","500 s","2 s","0.5 s"],
        ansIdx: 0,
        sol: "Period T = 1/f = 1/500 = 0.002 s.",
      },
      {
        q: "Which property of a sound wave determines its loudness?",
        options: ["Frequency","Amplitude","Wavelength","Speed"],
        ansIdx: 1,
        sol: "Loudness is determined by amplitude — a larger amplitude means a louder sound.",
      },
      {
        q: "The speed of sound is fastest in which medium?",
        options: ["Air","Water","Steel","Vacuum"],
        ansIdx: 2,
        sol: "Sound travels fastest in solids (steel), then liquids (water), then gases (air). It cannot travel in a vacuum.",
      },
      {
        q: "A police siren has a frequency of 800 Hz. The pitch appears higher as it approaches you. This is called:",
        options: ["The Doppler Effect","Resonance","Diffraction","The photoelectric effect"],
        ansIdx: 0,
        sol: "The apparent change in frequency due to relative motion is the Doppler Effect.",
      },
    ],
    quiz: [
      {
        q: "Sound waves are:",
        options: ["Electromagnetic waves","Transverse waves","Longitudinal waves","Surface waves"],
        ansIdx: 2,
        sol: "Sound waves are longitudinal — particles vibrate parallel to the direction of wave travel.",
      },
      {
        q: "Doubling the frequency of a sound wave will:",
        options: ["Halve the wavelength (at constant speed)","Double the speed","Halve the amplitude","Have no effect on wavelength"],
        ansIdx: 0,
        sol: "Since v = fλ, if speed v is constant, doubling f halves λ.",
      },
      {
        q: "0 dB represents:",
        options: ["No sound at all","The threshold of human hearing","The loudest possible sound","The speed of sound"],
        ansIdx: 1,
        sol: "0 dB is defined as the quietest sound a healthy human ear can detect (threshold of hearing).",
      },
    ],
  },
  { // ch03 - Phase Changes
    id: "ch03",
    g: "8",
    gx: 1,
    title: "Heat and Phase Changes",
    coverage: "g",
    think: "Why does ice melt but water also evaporate? What happens to the temperature during a phase change? Why does sweating cool you down?",
    videos: [
      { yt: "DqHxyjmKz1w", t: "Heat and Temperature" },
      { yt: "DqHxyjmKz1w", t: "Changing States Part 1" },
      { yt: "DqHxyjmKz1w", t: "Changing States Part 2" },
      { yt: "DqHxyjmKz1w", t: "Effect of Heat and Temperature" },
      { yt: "O7T0TpwvzGw", t: "Specific Heat" },
      { yt: "DqHxyjmKz1w", t: "Latent Heat" },
      { yt: "DqHxyjmKz1w", t: "Conduction" },
    ],
    subtopics: [
      { name: "Temperature and Heat", vids: [0,1], pq: [0,1,2] },
      { name: "Phase Changes", vids: [2,3,5], pq: [3,4,5,6] },
      { name: "Heat Transfer", vids: [6], pq: [7,8] },
    ],
    notes: [
      "Temperature: measure of average kinetic energy of particles.",
      "Heat: transfer of thermal energy.",
      "Specific heat: energy needed to raise 1 kg by 1°C.",
      "Latent heat: energy absorbed/released during phase change without temperature change.",
      "Q = mcΔT. Q = mL for phase changes.",
    ],
    practice: [
      {
        q: "During melting, the temperature of ice water remains at 0°C because:",
        options: ["No heat is being added","The heat is used to break bonds, not raise temperature","The ice is colder than water","The water is evaporating"],
        ansIdx: 1,
        sol: "Latent heat of fusion is absorbed to break the bonds between solid molecules, not to increase temperature.",
      },
      {
        q: "Which method of heat transfer is most important for heating a pot of water on a stove?",
        options: ["Conduction","Convection","Radiation","Evaporation"],
        ansIdx: 1,
        sol: "Convection (rising hot water + sinking cold water) circulates heat throughout the liquid.",
      },
      {
        q: "50 g of water at 20°C is heated to 70°C. How much heat is absorbed? (c = 4,200 J/(kg·°C))",
        options: ["10,500 J","10.5 J","105 J","1,050 J"],
        ansIdx: 0,
        sol: "Q = mcΔT = 0.05 kg × 4,200 × 50 = 10,500 J.",
      },
      {
        q: "Which has more thermal energy: 1 kg of water at 50°C or 1 kg of iron at 50°C?",
        options: ["Water","Iron","They have the same thermal energy","Cannot be determined"],
        ansIdx: 0,
        sol: "Water has a much higher specific heat than iron, so at the same mass and temperature, water contains more thermal energy.",
      },
      {
        q: "Evaporation cools the skin because:",
        options: ["It removes heat from the skin to vaporize sweat","It adds cold air to the skin","It absorbs sunlight","It increases air temperature"],
        ansIdx: 0,
        sol: "Latent heat of vaporization is absorbed from the skin when sweat evaporates, causing a cooling effect.",
      },
    ],
    quiz: [
      {
        q: "The specific heat capacity of a substance is:",
        options: ["The total heat it contains","Heat needed to raise 1 kg by 1°C","The temperature at which it melts","Heat released when it solidifies"],
        ansIdx: 1,
        sol: "Specific heat capacity (c) = energy / (mass × temperature change).",
      },
      {
        q: "Which state of matter has particles with the most kinetic energy?",
        options: ["Solid","Liquid","Gas","All have the same"],
        ansIdx: 2,
        sol: "Gas particles move fastest and have the most kinetic energy at the same temperature.",
      },
      {
        q: "Melting and boiling both require:",
        options: ["A temperature change","Absorption of latent heat","Release of latent heat","Constant pressure"],
        ansIdx: 1,
        sol: "Both phase changes absorb latent heat — heat of fusion or heat of vaporization — without changing temperature.",
      },
    ],
  },
  { // ch04 - Light
    id: "ch04",
    g: "8",
    gx: 1,
    title: "Light and Optics",
    coverage: "g",
    think: "Why can you see your reflection in a mirror but not in a wall? What makes the sky blue and sunsets red? Why does a straw look bent in water?",
    videos: [
      { yt: "VFrqkY3SI4w", t: "Introduction to Light" },
      { yt: "55jzZ0t2D50", t: "Reflection and Mirrors" },
      { yt: "55jzZ0t2D50", t: "Reflection Laws and Ray Diagrams" },
      { yt: "55jzZ0t2D50", t: "Refraction" },
      { yt: "55jzZ0t2D50", t: "Dispersion" },
      { yt: "55jzZ0t2D50", t: "Total Internal Reflection" },
      { yt: "55jzZ0t2D50", t: "Mirrors" },
    ],
    subtopics: [
      { name: "Light Basics", vids: [0], pq: [0,1] },
      { name: "Reflection", vids: [1,2], pq: [2,3,4] },
      { name: "Refraction", vids: [3,4,5], pq: [5,6,7] },
    ],
    notes: [
      "Light is a transverse electromagnetic wave.",
      "Law of reflection: angle of incidence = angle of reflection.",
      "Refraction: bending of light when changing medium.",
      "Speed of light in vacuum c = 3×10⁸ m/s.",
      "Total internal reflection occurs when angle > critical angle.",
    ],
    practice: [
      {
        q: "The angle of incidence is 30°. What is the angle of reflection?",
        options: ["60°","30°","90°","15°"],
        ansIdx: 1,
        sol: "Law of reflection: angle of incidence = angle of reflection = 30°.",
      },
      {
        q: "A ray of light goes from glass to air. If the angle of incidence is 40°, what happens?",
        options: ["It bends towards the normal","It bends away from the normal","It reflects back into the glass","It travels straight"],
        ansIdx: 1,
        sol: "Light bends away from the normal when going from denser (glass) to rarer (air) medium.",
      },
      {
        q: "A person stands 2 m in front of a flat mirror. How far away does their reflection appear to be?",
        options: ["2 m","4 m","1 m","8 m"],
        ansIdx: 1,
        sol: "The image appears the same distance behind the mirror as the object is in front: 2 m + 2 m = 4 m.",
      },
      {
        q: "The sky appears blue because:",
        options: ["Blue light is scattered most by the atmosphere","Blue light travels fastest","Blue light is absorbed by clouds","Blue light is reflected from the ocean"],
        ansIdx: 0,
        sol: "Rayleigh scattering: shorter wavelengths (blue) scatter more than longer wavelengths (red) in the atmosphere.",
      },
      {
        q: "Which phenomenon explains why a coin appears raised in water?",
        options: ["Reflection","Total internal reflection","Refraction","Diffraction"],
        ansIdx: 2,
        sol: "Refraction bends light from the coin, making it appear higher than it actually is.",
      },
    ],
    quiz: [
      {
        q: "In a plane mirror, the image is:",
        options: ["Real and inverted","Real and upright","Virtual and inverted","Virtual and upright"],
        ansIdx: 3,
        sol: "A plane mirror always produces a virtual (behind the mirror), upright image.",
      },
      {
        q: "A converging lens is also called a:",
        options: ["Concave lens","Convex lens","Plane lens","Diverging lens"],
        ansIdx: 1,
        sol: "A convex lens is thicker in the middle and converges parallel rays to a focal point.",
      },
      {
        q: "Total internal reflection requires:",
        options: ["Light going from rarer to denser medium","Light going from denser to rarer medium at angle > critical angle","Any change of medium","Light in a vacuum"],
        ansIdx: 1,
        sol: "TIR occurs only when light travels from a denser to rarer medium at an angle exceeding the critical angle.",
      },
    ],
  },
  { // ch05 - Lenses
    id: "ch05",
    g: "8",
    gx: 1,
    title: "Lenses and Vision",
    coverage: "g",
    think: "How does a magnifying glass work? Why do some people need glasses? How does the human eye focus light exactly like a camera?",
    videos: [
      { yt: "55jzZ0t2D50", t: "Parts of Eye" },
      { yt: "55jzZ0t2D50", t: "Defects of Vision" },
      { yt: "55jzZ0t2D50", t: "Convex Lenses" },
      { yt: "55jzZ0t2D50", t: "Concave Lenses" },
      { yt: "55jzZ0t2D50", t: "Lens Formula" },
      { yt: "55jzZ0t2D50", t: "Magnification" },
      { yt: "55jzZ0t2D50", t: "Human Eye" },
      { yt: "55jzZ0t2D50", t: "Telescope" },
    ],
    subtopics: [
      { name: "Human Eye", vids: [0,6], pq: [0,1,2] },
      { name: "Lens Types", vids: [2,3], pq: [3,4,5] },
      { name: "Lens Formula", vids: [4,5], pq: [6,7] },
    ],
    notes: [
      "Convex (converging) lens: thicker in middle, focal point in front.",
      "Concave (diverging) lens: thinner in middle, focal point behind.",
      "1/v + 1/u = 1/f (lens formula, all distances from optical centre).",
      "Magnification m = image height / object height = v/u.",
      "Human eye: cornea + lens focus image on retina.",
    ],
    practice: [
      {
        q: "An object is placed 30 cm from a convex lens with focal length 10 cm. Where is the image formed?",
        options: ["15 cm from lens","10 cm from lens","60 cm from lens","30 cm from lens"],
        ansIdx: 0,
        sol: "1/v = 1/f − 1/u = 1/10 − 1/30 = 2/30, so v = 15 cm.",
      },
      {
        q: "A concave lens always produces what type of image?",
        options: ["Real and inverted","Real and magnified","Virtual and upright","Virtual and inverted"],
        ansIdx: 2,
        sol: "Concave lenses always produce virtual, upright, diminished (smaller) images on the same side as the object.",
      },
      {
        q: "A person with myopia (nearsightedness) cannot see distant objects clearly because:",
        options: ["The eye is too short","The image focuses behind the retina","The eye is too long or lens too powerful","The cornea is too curved"],
        ansIdx: 2,
        sol: "Myopia: image focuses in front of the retina. Corrected with concave (diverging) lens.",
      },
      {
        q: "The focal length of a convex lens depends on:",
        options: ["The object distance","The lens material and curvature","The image distance","The brightness of light"],
        ansIdx: 1,
        sol: "Focal length f depends on lens material (refractive index n) and curvature (radii R1, R2): 1/f = (n−1)(1/R1 − 1/R2).",
      },
      {
        q: "Magnification is positive for:",
        options: ["Real images","Inverted images","Upright images","All images"],
        ansIdx: 2,
        sol: "By convention, magnification m is positive for upright (virtual) images and negative for inverted (real) images.",
      },
    ],
    quiz: [
      {
        q: "A convex lens can produce a virtual image when the object is:",
        options: ["At the focus","Beyond 2F","Between F and the lens","At 2F"],
        ansIdx: 2,
        sol: "When object is between focus F and the convex lens, rays diverge and produce a virtual, upright, magnified image.",
      },
      {
        q: "Power of a lens is measured in:",
        options: ["Metres","Dioptres","Joules","Watts"],
        ansIdx: 1,
        sol: "Power P = 1/f (in metres), unit = dioptre (D). A 2D lens has focal length 0.5 m.",
      },
      {
        q: "A person with hyperopia (farsightedness) needs a:",
        options: ["Concave lens","Convex lens","Plane mirror","Diverging lens"],
        ansIdx: 1,
        sol: "Hyperopia: image focuses behind the retina. Corrected with convex (converging) lens.",
      },
    ],
  },
  { // ch06 - Mass, Volume and Density
    id: "ch06",
    g: "8",
    gx: 1,
    title: "Mass, Volume and Density",
    coverage: "g",
    think: "Why does iron sink but wood floats? Is mass the same as weight? If you have 1 kg of iron and 1 kg of cotton, which is heavier — and which has more volume?",
    videos: [
      { yt: "nTf4oFr6Sn4", t: "Fluids and Density" },
      { yt: "nTf4oFr6Sn4", t: "Volume Displacement" },
      { yt: "nTf4oFr6Sn4", t: "Specific Gravity" },
      { yt: "nTf4oFr6Sn4", t: "Mass and Weight" },
      { yt: "nTf4oFr6Sn4", t: "Density Calculation" },
      { yt: "nTf4oFr6Sn4", t: "Buoyancy" },
    ],
    subtopics: [
      { name: "Density Basics", vids: [0,4], pq: [0,1,2] },
      { name: "Mass vs Weight", vids: [3], pq: [3,4] },
      { name: "Applications", vids: [1,2,5], pq: [5,6,7] },
    ],
    notes: [
      "Density ρ = mass / volume (kg/m³ or g/cm³).",
      "1 g/cm³ = 1,000 kg/m³.",
      "Mass: amount of matter (constant). Weight: W = mg (varies with g).",
      "An object floats if ρ_object < ρ_fluid.",
      "Specific gravity = ρ_object / ρ_water.",
    ],
    practice: [
      {
        q: "A block has mass 200 g and volume 250 cm³. What is its density?",
        options: ["0.8 g/cm³","1.25 g/cm³","0.5 g/cm³","8 g/cm³"],
        ansIdx: 0,
        sol: "ρ = m/V = 200/250 = 0.8 g/cm³.",
      },
      {
        q: "Which will float in water (ρ_water = 1 g/cm³)?",
        options: ["Ice (0.9 g/cm³)","Iron (7.8 g/cm³)","Gold (19.3 g/cm³)","Steel (7.8 g/cm³)"],
        ansIdx: 0,
        sol: "An object floats if its density is less than that of water (ρ < 1 g/cm³). Ice (0.9) floats; iron and gold sink.",
      },
      {
        q: "The mass of an object is 10 kg on Earth. What is its mass on the Moon?",
        options: ["About 1.67 kg","About 10 kg","About 60 kg","About 0 kg"],
        ansIdx: 1,
        sol: "Mass is the amount of matter and is constant everywhere. Weight changes (W = mg); on the Moon, g ≈ 1.6 m/s² so weight ≈ 16 N, but mass remains 10 kg.",
      },
      {
        q: "A stone weighs 50 N on Earth. What is its mass? (g = 10 N/kg)",
        options: ["500 kg","5 kg","50 kg","0.2 kg"],
        ansIdx: 1,
        sol: "m = W/g = 50/10 = 5 kg.",
      },
      {
        q: "Specific gravity of a substance is 2.5. What does this tell us?",
        options: ["It is 2.5 times denser than water","It has 2.5 kg per m³","It is 2.5 times the volume of water","It has 2.5 times the mass of water"],
        ansIdx: 0,
        sol: "Specific gravity = ρ_substance / ρ_water. A value of 2.5 means the substance is 2.5× denser than water.",
      },
    ],
    quiz: [
      {
        q: "The density of a pure gold ring can be found by:",
        options: ["Weighing it","Measuring volume in water only","Dividing mass by volume (using water displacement)","Multiplying mass by gravity"],
        ansIdx: 2,
        sol: "Density = mass/volume. Volume is found by water displacement: V = V_water_with_object − V_water_alone.",
      },
      {
        q: "A 1 kg object and a 10 kg object are both in free fall. They have:",
        options: ["The same acceleration and the same weight","Different accelerations but the same weight","The same acceleration but different weights","Different accelerations and different weights"],
        ansIdx: 0,
        sol: "All objects in free fall have the same acceleration g (9.8 m/s²). Weight differs (W = mg) but doesn't affect free-fall acceleration.",
      },
      {
        q: "When ice melts in a full glass of water, the water level:",
        options: ["Rises (spills over)","Falls","Stays the same","Depends on the temperature"],
        ansIdx: 2,
        sol: "Floating ice displaces its own weight of water. When it melts, it becomes water of the same weight, so the volume is identical — level stays the same.",
      },
    ],
  },
  { // ch07 - Force
    id: "ch07",
    g: "8",
    gx: 1,
    title: "Forces and Newton's Laws",
    coverage: "g",
    think: "If you push a table and it doesn't move, are you applying a force? Why does a seatbelt protect you in a crash? If action equals reaction, how does anything ever move?",
    videos: [
      { yt: "kK8XzkVlKk0", t: "Newton's First Law" },
      { yt: "kK8XzkVlKk0", t: "More on Newton's First Law" },
      { yt: "F633rKExz0c", t: "Newton's Second Law" },
      { yt: "C7eO2-ESz5E", t: "Newton's Third Law" },
      { yt: "C7eO2-ESz5E", t: "Free Body Diagrams" },
      { yt: "C7eO2-ESz5E", t: "Friction" },
      { yt: "C7eO2-ESz5E", t: "Tension" },
    ],
    subtopics: [
      { name: "Newton's First Law", vids: [0,1], pq: [0,1,2] },
      { name: "Newton's Second Law", vids: [2], pq: [3,4,5,6] },
      { name: "Newton's Third Law", vids: [3,4], pq: [7,8] },
    ],
    notes: [
      "Newton's 1st Law (Inertia): object at rest stays at rest unless acted upon by net external force.",
      "Newton's 2nd Law: F = ma.",
      "Newton's 3rd Law: Every action has an equal and opposite reaction.",
      "Friction f = μN (normal force × coefficient).",
      "Net force = vector sum of all forces on the object.",
    ],
    practice: [
      {
        q: "A 5 kg object is pulled with a force of 20 N. What is its acceleration?",
        options: ["4 m/s²","100 m/s²","0.25 m/s²","25 m/s²"],
        ansIdx: 0,
        sol: "F = ma → a = F/m = 20/5 = 4 m/s².",
      },
      {
        q: "A book rests on a table. According to Newton's Third Law, the reaction force to the book's weight is:",
        options: ["The table pushing up on the book","The book pulling the Earth upward","The book pressing down on the table","The table pressing down on the floor"],
        ansIdx: 1,
        sol: "Action-reaction pairs act on different objects. The book's weight acts downward on the table; the reaction is the book pulling the Earth upward with equal force.",
      },
      {
        q: "A car moving at constant velocity of 20 m/s has:",
        options: ["A net force in the direction of motion","A net force of zero","A decreasing net force","Cannot be determined"],
        ansIdx: 1,
        sol: "Constant velocity means zero acceleration, so net force = ma = 0. All forces are balanced.",
      },
      {
        q: "Two forces, 8 N right and 5 N left, act on a 2 kg object. What is the acceleration?",
        options: ["1.5 m/s² right","6.5 m/s² left","1.5 m/s² left","6.5 m/s² right"],
        ansIdx: 0,
        sol: "Net force = 8 − 5 = 3 N right. a = F/m = 3/2 = 1.5 m/s² to the right.",
      },
      {
        q: "Which of the following best describes inertia?",
        options: ["The tendency to resist changes in motion","The force that keeps objects moving","The acceleration due to gravity","The frictional force"],
        ansIdx: 0,
        sol: "Inertia = resistance to change in motion. Newton's 1st Law states objects with inertia keep their state of motion unless acted upon.",
      },
    ],
    quiz: [
      {
        q: "A 3 kg object has an acceleration of 4 m/s². What is the net force acting on it?",
        options: ["12 N","7 N","1.33 N","0.75 N"],
        ansIdx: 0,
        sol: "F = ma = 3 × 4 = 12 N.",
      },
      {
        q: "When a bullet is fired from a rifle, the rifle recoils because:",
        options: ["Momentum is conserved — bullet goes forward, rifle goes backward","The rifle is lighter than the bullet","Friction between shooter and rifle","Air resistance pushes the rifle back"],
        ansIdx: 0,
        sol: "Conservation of momentum: total momentum before = after. Equal magnitudes, opposite directions. |m_rifle × v_rifle| = |m_bullet × v_bullet|.",
      },
      {
        q: "A book sliding on a table slows down because of:",
        options: ["Its inertia","Air resistance and friction","Its weight","The normal force"],
        ansIdx: 1,
        sol: "Without forces, inertia keeps it moving forever. Friction and air resistance are external forces that change its momentum.",
      },
    ],
  },
  { // ch08 - Pressure
    id: "ch08",
    g: "8",
    gx: 1,
    title: "Pressure",
    coverage: "g",
    think: "Why can a sharp knife cut but a blunt one can't? Why do wide tires grip better than narrow ones? Why do deep-sea fish explode if brought to the surface?",
    videos: [
      { yt: "nTf4oFr6Sn4", t: "What is Pressure" },
      { yt: "nTf4oFr6Sn4", t: "Fluid Pressure" },
      { yt: "nTf4oFr6Sn4", t: "Pressure in Liquids" },
      { yt: "nTf4oFr6Sn4", t: "Pressure in Gases" },
      { yt: "nTf4oFr6Sn4", t: "Atmospheric Pressure" },
      { yt: "nTf4oFr6Sn4", t: "Pascal's Principle" },
    ],
    subtopics: [
      { name: "Pressure Basics", vids: [0], pq: [0,1,2] },
      { name: "Fluid Pressure", vids: [1,2,5], pq: [3,4,5] },
      { name: "Atmospheric Pressure", vids: [3,4], pq: [6,7] },
    ],
    notes: [
      "Pressure P = Force / Area (N/m² = Pascal, Pa).",
      "Liquid pressure P = ρgh (depth × density × g).",
      "Atmospheric pressure at sea level ≈ 101,325 Pa ≈ 10⁵ Pa.",
      "Pascal's Principle: pressure change transmits equally throughout a fluid.",
      "Pressure acts in all directions at a given depth in a fluid.",
    ],
    practice: [
      {
        q: "A 500 N person stands on one foot (area 150 cm²). What pressure is exerted on the floor?",
        options: ["3.33×10⁴ Pa","3.33 Pa","33.3 Pa","333 Pa"],
        ansIdx: 0,
        sol: "P = F/A = 500 N / (0.015 m²) = 33,333 Pa ≈ 3.33 × 10⁴ Pa.",
      },
      {
        q: "At a depth of 10 m in water (ρ = 1,000 kg/m³), the pressure is:",
        options: ["98,000 Pa","10,000 Pa","100,000 Pa","9,800 Pa"],
        ansIdx: 0,
        sol: "P = ρgh = 1,000 × 9.8 × 10 = 98,000 Pa = 98 kPa (plus atmospheric pressure adds ~101 kPa more).",
      },
      {
        q: "Why do wide snowshoes let you walk on snow without sinking?",
        options: ["They decrease pressure by increasing area","They decrease force","They increase mass","They reduce gravity"],
        ansIdx: 0,
        sol: "P = F/A. Same weight (F = mg) spread over a larger area → lower pressure → less sinking.",
      },
      {
        q: "A hydraulic lift uses Pascal's principle. If the input piston has area 5 cm² and output has 100 cm², a force of 50 N on the input produces what output force?",
        options: ["1,000 N","10 N","2,500 N","50 N"],
        ansIdx: 0,
        sol: "P₁ = P₂ → F₁/A₁ = F₂/A₂ → 50/5 = F₂/100 → F₂ = 50 × 20 = 1,000 N.",
      },
      {
        q: "Atmospheric pressure is caused by:",
        options: ["Weight of the air above us","Temperature of the air","Water vapor in the air","Electric forces between molecules"],
        ansIdx: 0,
        sol: "Atmospheric pressure = weight of the column of air above a unit area. ~10⁵ Pa at sea level.",
      },
    ],
    quiz: [
      {
        q: "Pressure in a liquid at the same depth is:",
        options: ["The same in all directions","Greater upward than downward","Greater downward than upward","Zero"],
        ansIdx: 0,
        sol: "At a given depth, pressure acts equally in all directions — up, down, and sideways.",
      },
      {
        q: "If you go up a mountain, atmospheric pressure:",
        options: ["Decreases (less air above)","Increases","Stays the same","Becomes zero"],
        ansIdx: 0,
        sol: "As altitude increases, there is less air above, so atmospheric pressure decreases.",
      },
      {
        q: "A dam is thicker at the bottom because:",
        options: ["Pressure in water increases with depth","Water is heavier at the bottom","Water flows faster at the bottom","The dam needs to support its own weight"],
        ansIdx: 0,
        sol: "P = ρgh. Deeper water exerts more pressure, so the dam must be stronger (thicker) at the bottom.",
      },
    ],
  },
  { // ch09 - Buoyancy
    id: "ch09",
    g: "8",
    gx: 1,
    title: "Buoyancy",
    coverage: "g",
    think: "Why can a huge steel ship float even though steel is denser than water? Is your weight the same in a pool as on land? How does a submarine rise and sink at will?",
    videos: [
      { yt: "nTf4oFr6Sn4", t: "Buoyant Force" },
      { yt: "nTf4oFr6Sn4", t: "What is Buoyant Force" },
      { yt: "nTf4oFr6Sn4", t: "Archimedes' Principle" },
      { yt: "nTf4oFr6Sn4", t: "Buoyancy and Density" },
      { yt: "nTf4oFr6Sn4", t: "Floating and Sinking" },
      { yt: "nTf4oFr6Sn4", t: "Apparent Weight" },
    ],
    subtopics: [
      { name: "Archimedes' Principle", vids: [0,1,2], pq: [0,1,2] },
      { name: "Floating and Sinking", vids: [3,4], pq: [3,4,5] },
      { name: "Applications", vids: [5], pq: [6,7] },
    ],
    notes: [
      "Archimedes' Principle: Buoyant force = weight of displaced fluid.",
      "F_b = ρ_fluid × V_displaced × g.",
      "Object floats: F_b = W_object (buoyant force = weight).",
      "Object sinks: ρ_object > ρ_fluid.",
      "Apparent weight = true weight − buoyant force.",
    ],
    practice: [
      {
        q: "A 1 kg wooden block (ρ = 0.6 g/cm³) floats in water. What fraction of its volume is submerged?",
        options: ["60%","40%","100%","0.6%"],
        ansIdx: 0,
        sol: "For floating: F_b = W → ρ_water × V_sub × g = ρ_block × V_total × g → V_sub/V_total = ρ_block/ρ_water = 0.6/1.0 = 0.6 = 60%.",
      },
      {
        q: "A stone weighs 30 N in air and 20 N when fully underwater. What is the buoyant force?",
        options: ["10 N","20 N","30 N","50 N"],
        ansIdx: 0,
        sol: "F_b = W_apparent = W_true − W_apparent = 30 − 20 = 10 N.",
      },
      {
        q: "A steel ship floats because:",
        options: ["It displaces enough water to equal its weight","Steel is lighter than water","The air inside is lighter than water","Water pushes it up from below"],
        ansIdx: 0,
        sol: "The ship's hull displaces a volume of water equal to its total weight. Average density (steel + air) < density of water.",
      },
      {
        q: "An object with density 0.8 g/cm³ is placed in water. What happens?",
        options: ["It floats with 80% submerged","It sinks slowly","It floats with 20% submerged","It stays suspended at mid-depth"],
        ansIdx: 0,
        sol: "ρ < 1 g/cm³ (water) → object floats. 80% of its volume is submerged (0.8/1.0).",
      },
      {
        q: "The buoyant force on a 1 m³ block fully submerged in water is:",
        options: ["9,800 N upward","9,800 N downward","98 N upward","1,000 N upward"],
        ansIdx: 0,
        sol: "F_b = ρVg = 1,000 × 1 × 9.8 = 9,800 N upward (equal to weight of displaced water).",
      },
    ],
    quiz: [
      {
        q: "Two spheres of equal volume, one iron (ρ = 7.8 g/cm³) and one aluminum (ρ = 2.7 g/cm³), are both fully submerged in water. Which has greater buoyant force?",
        options: ["They have equal buoyant force","The iron sphere","The aluminum sphere","Cannot be determined without knowing volume"],
        ansIdx: 0,
        sol: "F_b = ρ_water × V_displaced × g. Equal volume → equal buoyant force on both. (Their weights differ, but buoyant force is the same.)",
      },
      {
        q: "A helium balloon rises because:",
        options: ["Helium is less dense than air, so buoyant force > balloon weight","Helium weighs nothing","Air pushes the balloon up from below","Gravity does not act on helium"],
        ansIdx: 0,
        sol: "ρ_helium < ρ_air → weight of displaced air > weight of helium + balloon. Net upward force = buoyant force − weight.",
      },
      {
        q: "When a floating ice cube melts in a glass of water, the water level:",
        options: ["Stays the same","Rises","Falls","First rises then falls"],
        ansIdx: 0,
        sol: "Ice floats with part of its volume above water. Melting: the ice volume equals the water volume that was displaced. No change in water level.",
      },
    ],
  },
  { // ch10 - Work and Energy
    id: "ch10",
    g: "8",
    gx: 1,
    title: "Work and Energy",
    coverage: "g",
    think: "If you push a wall and it doesn't move, have you done work? Does a moving object always have kinetic energy? Can energy be created or destroyed?",
    videos: [
      { yt: "kK8XzkVlKk0", t: "Introduction to Work and Energy" },
      { yt: "kK8XzkVlKk0", t: "Kinetic Energy" },
      { yt: "kK8XzkVlKk0", t: "Potential Energy" },
      { yt: "kK8XzkVlKk0", t: "Conservation of Energy" },
      { yt: "kK8XzkVlKk0", t: "Power" },
      { yt: "kK8XzkVlKk0", t: "Mechanical Advantage" },
    ],
    subtopics: [
      { name: "Work", vids: [0], pq: [0,1,2] },
      { name: "Energy", vids: [1,2], pq: [3,4,5] },
      { name: "Conservation", vids: [3,4], pq: [6,7] },
    ],
    notes: [
      "Work W = F × d × cos θ (F and d in same direction).",
      "1 Joule = 1 N × 1 m.",
      "Kinetic energy KE = ½mv².",
      "Potential energy PE = mgh (gravitational).",
      "Law of conservation of energy: energy transforms, not created/destroyed.",
      "Power P = W/t = energy transferred per second (Watt = J/s).",
    ],
    practice: [
      {
        q: "A force of 50 N moves an object 4 m. How much work is done?",
        options: ["200 J","12.5 J","200 N","54 J"],
        ansIdx: 0,
        sol: "W = F × d = 50 × 4 = 200 J.",
      },
      {
        q: "You push a heavy box with 100 N of force but it doesn't move. How much work is done?",
        options: ["0 J","100 J","Cannot be determined","1000 J"],
        ansIdx: 0,
        sol: "Work requires both force and displacement (motion). No displacement → W = 0 J.",
      },
      {
        q: "A 2 kg ball is dropped from 5 m. What is its kinetic energy just before hitting the ground?",
        options: ["100 J","10 J","50 J","98 J"],
        ansIdx: 0,
        sol: "PE at top = mgh = 2 × 10 × 5 = 100 J. By conservation of energy, KE at ground = PE at top = 100 J.",
      },
      {
        q: "A 1,000 kg car moves at 20 m/s. What is its kinetic energy?",
        options: ["200,000 J","40,000 J","10,000 J","20,000 J"],
        ansIdx: 0,
        sol: "KE = ½mv² = ½ × 1,000 × 20² = 500 × 400 = 200,000 J.",
      },
      {
        q: "A motor lifts a 200 kg load 10 m in 5 seconds. What is its power output?",
        options: ["4,000 W","2,000 W","20,000 W","1,000 W"],
        ansIdx: 0,
        sol: "W = mgh = 200 × 10 × 10 = 20,000 J. P = W/t = 20,000/5 = 4,000 W.",
      },
    ],
    quiz: [
      {
        q: "A pendulum swings from height h to the bottom. Its speed at the bottom is determined by:",
        options: ["The height h (conservation of energy)","The mass of the pendulum","The length of the string","The angle of release"],
        ansIdx: 0,
        sol: "PE at height h = KE at bottom: mgh = ½mv². Mass cancels out — speed depends only on height, not mass.",
      },
      {
        q: "If you do 500 J of work to lift a box and it gains 500 J of potential energy, this illustrates:",
        options: ["Conservation of energy","Newton's second law","Pascal's principle","Archimedes' principle"],
        ansIdx: 0,
        sol: "Energy cannot be created or destroyed. Work input = energy gained (in ideal conditions).",
      },
      {
        q: "Which of the following has the most kinetic energy? (All have same mass.)",
        options: ["Bullet (500 m/s)","Car (30 m/s)","Runner (10 m/s)","Bicycle (5 m/s)"],
        ansIdx: 0,
        sol: "KE = ½mv². Same mass, highest velocity → largest KE. 500² = 250,000 >> 30² = 900.",
      },
    ],
  },
  { // ch11 - Simple Machines
    id: "ch11",
    g: "8",
    gx: 1,
    title: "Simple Machines",
    coverage: "g",
    think: "Why is a crowbar useful for prying open a lid? Why do ramps make lifting easier? If a lever makes work easier, where is the trade-off?",
    videos: [
      { yt: "kK8XzkVlKk0", t: "What are Simple Machines" },
      { yt: "kK8XzkVlKk0", t: "Mechanical Advantage" },
      { yt: "kK8XzkVlKk0", t: "Levers" },
      { yt: "kK8XzkVlKk0", t: "Pulleys" },
      { yt: "kK8XzkVlKk0", t: "Inclined Planes" },
      { yt: "kK8XzkVlKk0", t: "Wheel and Axle" },
      { yt: "kK8XzkVlKk0", t: "Gears" },
    ],
    subtopics: [
      { name: "Basic Concepts", vids: [0,1], pq: [0,1,2] },
      { name: "Levers", vids: [2], pq: [3,4,5] },
      { name: "Other Machines", vids: [3,4,5], pq: [6,7] },
    ],
    notes: [
      "Mechanical Advantage (MA) = Output force / Input force.",
      "Ideal MA = distance input / distance output (conservation of energy).",
      "Levers: 1st class (fulcrum in middle), 2nd (load in middle), 3rd (effort in middle).",
      "Pulley systems: MA = number of supporting rope segments.",
      "Inclined plane: MA = length of slope / height.",
      "No machine can give a mechanical advantage > 1 without requiring a greater input distance.",
    ],
    practice: [
      {
        q: "A lever has effort arm 2 m and load arm 0.5 m. What is its mechanical advantage?",
        options: ["4","0.5","2.5","1"],
        ansIdx: 0,
        sol: "MA = effort arm / load arm = 2/0.5 = 4. Can lift 4× heavier loads with 4× greater input distance.",
      },
      {
        q: "A fixed pulley has MA = 1. What is the advantage?",
        options: ["Changes direction of force only","Multiplies force by 2","Makes work zero","Increases energy"],
        ansIdx: 0,
        sol: "Fixed pulley has MA = 1 (no force advantage). Its benefit is changing the direction of the applied force (pull down to lift up).",
      },
      {
        q: "A block is pulled up an inclined plane of length 6 m to a height of 2 m. What is the ideal mechanical advantage?",
        options: ["3","0.33","4","8"],
        ansIdx: 0,
        sol: "IMA = slope length / height = 6/2 = 3.",
      },
      {
        q: "A wheelbarrow is an example of which class of lever?",
        options: ["Second class lever","First class lever","Third class lever","Not a lever"],
        ansIdx: 0,
        sol: "Second class lever: load is between fulcrum and effort (wheel = fulcrum, load in middle, handles = effort).",
      },
      {
        q: "A block and tackle pulley system has 4 supporting rope segments. What is the theoretical MA?",
        options: ["4","2","1","0.25"],
        ansIdx: 0,
        sol: "MA = number of rope segments supporting the load = 4. Each segment carries ¼ of the load.",
      },
    ],
    quiz: [
      {
        q: "In a first-class lever, where is the fulcrum?",
        options: ["Between the effort and the load","At the end, under the load","At the end, where effort is applied","Inside the lever"],
        ansIdx: 0,
        sol: "First-class lever: fulcrum (pivot) is between effort and load. Examples: seesaw, scissors, crowbar.",
      },
      {
        q: "A nutcracker is a second-class lever because:",
        options: ["Load is between fulcrum and effort","Effort is between fulcrum and load","Fulcrum is between effort and load","None of the above"],
        ansIdx: 0,
        sol: "Second class: load in the middle. In a nutcracker, the hinge is the fulcrum, nut is the load, handles are the effort.",
      },
      {
        q: "Which statement about simple machines is always true?",
        options: ["They make work easier by trading distance for force","They reduce the total work done","They increase total energy","They eliminate friction"],
        ansIdx: 0,
        sol: "Simple machines trade force for distance (or vice versa). Work in = work out (ignoring friction). You use less force over a greater distance.",
      },
    ],
  },
];
